packages:
  - ch03/*
  - ch04/*
  - ch05/*
  - ch06/*
  - ch07/*
  - ch08/*
  - ch09/*
  - ch10/*
  - ch11/*
  - ch12/*
  - ch13/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@scarf/scarf'
  - core-js
  - cypress
  - esbuild
  - node-rdkafka
  - nx
  - prisma
  - protobufjs
  - unrs-resolver
